python trainers/train_vitvqvae.py \
    --model_from_checkpoint \
    --model_checkpoint_path './models/vitvqvae/model.pt' \
    --transformer_from_checkpoint \
    --transformer_checkpoint_path './models/vitvqvae/model_gen.pt' \
    --mode 'generate' \
    --num_new_images 1 \
    --batch_size 256 \
    --model_dir './models/vitvqvae' \
    --epochs 500 \
    --latent_dim 64 \
    --num_embeddings 512 \
    --image_channels 3 \
    --image_size 32 \
    --patch_size 4 \
    --beta 0.25 \
    --lr 0.001 \
    --num_heads 4 \
    --num_blocks 2 \
    --dropout 0.01 \
    --keep_prob 0.8

