wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.11.4
    cli_version: 0.16.6
    framework: huggingface
    huggingface_version: 4.38.2
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1712493838.0
    t:
      1:
      - 1
      - 11
      - 41
      - 49
      - 55
      - 71
      2:
      - 1
      - 11
      - 41
      - 49
      - 55
      - 71
      3:
      - 23
      4: 3.11.4
      5: 0.16.6
      6: 4.38.2
      8:
      - 5
      13: linux-x86_64
input_res:
  desc: null
  value:
  - 64
  - 64
patch_size:
  desc: null
  value: 4
num_channels:
  desc: null
  value: 3
num_codebook_embeddings:
  desc: null
  value: 1024
codebook_dim:
  desc: null
  value: 32
num_layers:
  desc: null
  value: 1
num_heads:
  desc: null
  value: 4
num_blocks:
  desc: null
  value: 2
model_name:
  desc: null
  value: Meow
with_vq:
  desc: null
  value: true
gradient_accumulation_steps:
  desc: null
  value: 2
epochs:
  desc: null
  value: 1
batch_size:
  desc: null
  value: 256
from_checkpoint:
  desc: null
  value: false
